### ISSUE TITLE
Is there a way to exclude sending images?

### ISSUE THREAD

**Issue by shayonpal** [Masterb1234/obsidian-post-webhook#1]
I am trying to set up some automations via Zapier, and looks like they don't accept webhook requests over 2mb. The images' base64 info is overshooting that limit.

**Comment by Masterb1234** [comment]
Hi Shayon,

Currently, the plugin doesn’t support sending notes without attachments. However, that’s a great suggestion! I plan to add support for this, likely by allowing the exclusion of (all) attachments via YAML, in the next release.

**Comment by Masterb1234** [comment]
I've added a feature that allows attachments to be excluded from the payload in YAML, which should help reduce the payload size and resolve the issue with Zapier's limit.

Please update to the latest version (v1.1.2) and use the new option to exclude attachments:
---
exclude-attachment:
  - image1.png
  - file3.mp3
---
If you encounter any further issues or need assistance setting it up, feel free to let me know.

**Comment by shayonpal** [comment]
Thanks. I appreciate the quick TAT. I updated the plugin, but couldn't find a way to exclude the attachments. Am I supposed to add that info in the note's YAML?

![CleanShot 2024-12-23 at 16 47 04](https://github.com/user-attachments/assets/b8793069-5ff0-4472-b931-e03bf49ccb16)

**Comment by shayonpal** [comment]
I just noticed this. Thanks, but it doesn't solve my use case, since I'll have to make the change in too many notes, with too many attachments per note. Nevertheless, if ever you decide to allow excluding all attachments per webhook, I'll keep an eye out for that.

![CleanShot 2024-12-23 at 16 51 32](https://github.com/user-attachments/assets/b5a443f3-ed0f-4c9f-b3df-e8661c6033d8)

**Comment by shayonpal** [comment]
Apologies for spamming messages. I made this change in the code. This should stop sending the attachment files in the webhook, right?

![CleanShot 2024-12-23 at 16 57 34](https://github.com/user-attachments/assets/91747ec5-6c5a-411e-b176-05905cd72329)

**Comment by shayonpal** [comment]
I have an AI agent set up at Zapier that is grounded with YAML metadata that I use in my Vault. When I am done working on a note, I send that note to Zapier to get its YAML standardized, save it in Google Drive and have Hazel in my Mac mini server that looks for new files in that folder, analyses the YAML and files in it appropriate folder in my vault.

**Comment by Masterb1234** [comment]
That's pretty cool! I'll prioritize your suggestion.

**Comment by shayonpal** [comment]
Thanks. Appreciate it.

**Comment by Masterb1234** [comment]
I’ve added an option to exclude sending all attachments directly via the plugin’s settings (version: 1.2.0). I hope this works for your use case. Let me know if you run into any issues.

**Comment by shayonpal** [comment]
This is absolutely brilliant. Thank you so much! 🤘🏽
